// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home.title": "Welcome",
  "home.description": "This is the English version."
};
export default messages;