import type { Metadata } from "next";
import "./globals.css";
import "../style/markdown.css"
import NavBar from "@/components/Navigation";
import Footer from "@/components/Footer";
import { Ubuntu } from 'next/font/google'
import { ContextProvider } from "@/context/GeneralContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({ weight: ['400', '500', '700'], subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body
        className={`${ubuntu.className} antialiased`}
      >
        <NavBar />
        <div className="mb-20"></div>
        <ContextProvider>{children}</ContextProvider>
        <Footer />
      </body>
    </html>
  );
}
